services:
  php:
    build: ./docker/php
    working_dir: /app
    user: "${CURRENT_USER}"
    volumes:
      - .:/app
    depends_on:
      - rabbit
    environment:
      CURRENT_USER: '11:11'

  rabbit:
    build: ./docker/rabbit
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "8082:15672"